<?php
// $Id$

/**
* Display help and module information
*/
//require_once("./appsapis.php")
//require_once("provisioning.php")
#module_load_include('php', 'grupal', 'appsapis');

/**
* Valid permissions for this module
* @return array An array of valid permissions for the grupal module
*/
function grupal_perm() {
  return array('have google apps account', 'administer google apps');
} // function grupal_perm()

/**
* Display help and module information
* @param path which path of the site we're displaying help
* @param arg array that holds the current path as would be returned from arg() function
* @return help text for the path
*/
function grupal_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#grupal":
      $output = '<p>'.  t("Google Apps integrations for Drupal") .'</p>';
      break;
    case "admin/settings/grupal":
      $output = '<p>'.  t("Google Apps (http://google.com/a/)"). '</p>';
      break;
  }
  return $output;
} // function grupal_help

/**
* Menu items for this module
* @return array An array of menu items
*/
function grupal_menu() {

  $items['admin/settings/grupal'] = array(
    'path' => 'admin/settings/grupal',
    'title' => t('Google Apps module settings'),
    'callback' => 'drupal_get_form',
    'callback arguments' => 'grupal_admin',
    'access' => user_access('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
} // function grupal_menu

/**
* Admin form for this module
* @return system settings form
*/
function grupal_admin() {
  $form['global'] = array(
    '#type' => 'fieldset',
    '#title' => t('Google Apps service settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['global']['grupal_enabled'] = array(
    '#type' => 'radios',
    '#title' => t('Google Apps enabled'),
    '#default_value' => variable_get('grupal_enabled', 0),
    '#options' => array(t('Disabled'), t('Enabled')),
    '#description' => t("Google Apps integrations enabled or disabled.")
  );
  $form['global']['grupal_domain'] = array(
    '#type' => 'textfield',
    '#title' => t('Google Apps domain'),
    '#default_value' => variable_get('grupal_domain', 'example.com'),
    '#size' => 32,
    '#maxlength' => 255,
    '#description' => t("Google Apps domain, may differ from Drupal domain.")
  );
  $form['global']['grupal_admin_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Google Apps admin email'),
    '#default_value' => variable_get('grupal_admin_email', 'admin@example.com'),
    '#size' => 32,
    '#maxlength' => 128,
    '#description' => t("Google Apps administrator email.")
  );
  $form['global']['grupal_admin_pass'] = array(
    '#type' => 'password',
    '#title' => t('Google Apps admin password'),
    '#default_value' => variable_get('grupal_admin_pass', ''),
    '#size' => 16,
    '#maxlength' => 32,
    '#description' => t("Google Apps administrator password to be used to create accounts.")
  );
  $form['global']['grupal_account_status'] = array(
    '#type' => 'radios',
    '#title' => t('Google Apps account status on creation'),
    '#default_value' => variable_get('grupal_account_status', 1),
    '#options' => array(t('Disabled'), t('Enabled')),
    '#description' => t("Specify whether accounts should be enabled or suspended on creation.")
  );

  $form['email'] = array(
    '#type' => 'fieldset',
    '#title' => t('Google Apps email account settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['email']['grupal_email_quota'] = array(
    '#type' => 'textfield',
    '#title' => t('Mail quota'),
    '#default_value' => variable_get('grupal_email_quota', ''),
    '#size' => 6,
    '#maxlength' => 5,
    '#description' => t('Amount of space available for mail (Mb).'),
  );

  return system_settings_form($form);
} // function grupal_admin

/**
* Handle Drupal 'user' hook events
* http://api.drupal.org/api/function/hook_user
* @param op What kind of action is being performed.
* @param edit The array of form values submitted by the user. 
* @param account The user object on which the operation is being performed.
* @param category The active category of user information being edited.
* @return depends on operation, usually none.
*/
function grupal_user($op, &$edit, &$account, $category = NULL) {
  
  $grupal_domain = variable_get('grupal_domain', '');
  $grupal_username = grupal_cleanname($account->name);

  if ($op == 'insert') {
    // Create a new account on 'insert'
  }
  if ($op == 'update') {
    // Update Google Apps details on 'update'
  }
  if ($op == 'delete') {
    // Suspend or delete user on 'delete'
  }

} // function grupal_user

/**
* Filter unsupported characters from username
* @param name Drupal username
* @return Google Apps compatible clean username
*/
function grupal_cleanname($name) {
  return eregi_replace("[^a-z0-9\.]", "", strtolower($name));
} // function grupal_cleanname
